// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"基本的なパラメーターを設定するプラグインです。","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":false,"description":"メイン画面へ進む前に、\"Made with MV\"のスプラッシュ画面もしくはカスタマイズされたスプラッシュ画面を表示します。","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"Mano_KisekaeTrait","status":true,"description":"装備品にグラフィック変更特性を追加します","parameters":{"kisekae1":"{\"armor\":\"1\",\"characterIndex\":\"1\",\"characterName\":\"Actor1\",\"faceIndex\":\"0\",\"faceName\":\"Actor1\",\"battler\":\"Actor1_1\"}","kisekae2":"{\"armor\":\"5\",\"characterIndex\":\"0\",\"characterName\":\"poniko__neko_walk\",\"faceIndex\":\"0\",\"faceName\":\"poniko_neko\",\"battler\":\"\"}","kisekae3":"{\"armor\":\"2\",\"characterIndex\":\"0\",\"characterName\":\"poniko__hat_walk\",\"faceIndex\":\"0\",\"faceName\":\"poniko_hat\",\"battler\":\"\"}","kisekae4":"","kisekae5":"","kisekae6":"","kisekae7":"","kisekae8":"","kisekae9":"","kisekae10":"","kisekae11":"","kisekae12":"","kisekae13":"","kisekae14":"","kisekae15":"","kisekae16":"","kisekae17":"","kisekae18":"","kisekae19":"","kisekae20":""}},
{"name":"RTK_EnemySight","status":true,"description":"マップでイベントがプレイヤーを見かけるとスイッチをON","parameters":{"tag name":"sight","followers":"1","sight through":"0"}},
{"name":"TriggerOnEquipAndState","status":true,"description":"装備変更時の変数操作プラグイン","parameters":{"戦闘メンバーのみ":"false"}},
{"name":"SelfSwitchTemporary","status":true,"description":"一時セルフスイッチプラグイン","parameters":{}},
{"name":"MasterVolumeOption","status":true,"description":"マスターボリューム設定プラグイン","parameters":{"項目名称":"全体 音量","初期値":"10","音量の増減量":"5"}},
{"name":"YEP_RegionRestrictions","status":true,"description":"v1.04 Use regions to block out Events and/or the player from\r\nbeing able to venture into those spots.","parameters":{"Player Restrict":"0","Event Restrict":"1","All Restrict":"0","Player Allow":"0","Event Allow":"0","All Allow":"2"}},
{"name":"SimpleFollowerControl","status":true,"description":"v1.1 Allows you simple control over your followers.","parameters":{"Follower Collision":"false"}}
];
